# Generated by Django 5.1.6 on 2025-09-12 08:27

from django.db import migrations, models
from django.db.models import Subquery


def set_privacy_level(apps, schema_editor):
    model = apps.get_model("history", "Listening")
    Actor = apps.get_model("federation", "Actor")

    for privacy_level in ["me", "followers", "everyone", "instance"]:
        actors = Actor.objects.filter(user__privacy_level=privacy_level).values("pk")
        model.objects.filter(actor_id__in=Subquery(actors)).update(
            privacy_level=privacy_level
        )


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0004_listening_actor_listening_fid_listening_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listening",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("me", "Only me"),
                    ("followers", "Me and my followers"),
                    ("instance", "Everyone on my instance, and my followers"),
                    ("everyone", "Everyone, including people on other instances"),
                ],
                max_length=30,
                default="me",
            ),
        ),
        migrations.RunPython(set_privacy_level, reverse_code=migrations.RunPython.noop),
    ]
