# Generated by Django 5.1.6 on 2025-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0004_listening_actor_listening_fid_listening_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listening",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("me", "Only me"),
                    ("followers", "Me and my followers"),
                    ("instance", "Everyone on my instance, and my followers"),
                    ("everyone", "Everyone, including people on other instances"),
                ],
                max_length=30,
                default="me",
            ),
        ),
    ]
