# Generated by Django 5.1.6 on 2026-02-03 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0030_blockedactor_actor_blocked_actors"),
        ("history", "0005_alter_listening_privacy_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeningsScan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("errored_files", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=25)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("modification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="federation.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_scans",
                        to="federation.actor",
                    ),
                ),
            ],
        ),
    ]
