# Generated by Django 4.2.9 on 2025-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0007_alter_playlist_actor_alter_playlisttrack_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
