# Generated by Django 4.2.9 on 2024-10-18 20:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("radios", "0007_merge_20220715_0801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiosession",
            name="config",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
