services:
  sphinx:
    build:
      context: ../
      dockerfile: docs/Dockerfile
    init: true
    ports: ["8001:8001"]
    command: sh -c 'cd /src/docs && make dev'
    volumes:
      - ../docs:/src/docs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-funkwhale-docs-web.rule=Host(`docs.funkwhale.test`)"
      - "traefik.http.routers.test-funkwhale-docs-web.entrypoints=web"

      - "traefik.http.routers.test-funkwhale-docs-webs.rule=Host(`docs.funkwhale.test`)"
      - "traefik.http.routers.test-funkwhale-docs-webs.entrypoints=webs"
      - "traefik.http.routers.test-funkwhale-docs-webs.tls=true"
    networks: ["web"]
