services:
  traefik:
    image: traefik:mimolette
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./etc/traefik/dynamic:/etc/traefik/dynamic
      - ./var/test.key:/ssl/test.key
      - ./var/test.crt:/ssl/test.crt
    network_mode: host
