x-busybox: &busybox
  init: true
  image: 'busybox'
  network_mode: bridge
  dns: 172.17.0.1
  dns_search: funkwhale.test

networks:
  web:
    external: true

services:
  whoami:
    image: 'traefik/whoami'
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-web.rule=Host(`whoami.funkwhale.test`)'
      - 'traefik.http.routers.whoami-web.entrypoints=web'

      - 'traefik.http.routers.whoami-webs.rule=Host(`whoami.funkwhale.test`)'
      - 'traefik.http.routers.whoami-webs.entrypoints=webs'
      - 'traefik.http.routers.whoami-webs.tls=true'
      - 'traefik.http.routers.whoami.tls.domains[0].main=whoami.funkwhale.test'

  shell:
    <<: *busybox

  keep-docker0-up:
    <<: *busybox
    tty: true
