FROM node:22-alpine

# needed to compile translations
RUN apk add --no-cache jq bash coreutils git python3

WORKDIR /app/

# Create node_modules directory to prevent it from being hidden by volume mounts
RUN mkdir -p node_modules

ADD scripts/ ./scripts/
ADD package.json yarn.lock  ./
RUN yarn

VOLUME /app
VOLUME /app/node_modules
EXPOSE 8080

CMD ["yarn", "dev", "--host"]
