# Generated by Django 4.2.9 on 2025-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0059_remove_album_artist_remove_track_artist_artistcredit_and_more"),
        ("playlists", "0007_alter_playlist_actor_alter_playlisttrack_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="library",
            name="description",
        ),
        migrations.RemoveField(
            model_name="library",
            name="followers_url",
        ),
    ]
