# Generated by Django 4.2.9 on 2024-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0062_del_lib_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="third_party_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="uploadversion",
            name="mimetype",
            field=models.CharField(
                choices=[
                    ("audio/mp3", "mp3"),
                    ("audio/mpeg3", "mp3"),
                    ("audio/x-mp3", "mp3"),
                    ("audio/mpeg", "mp3"),
                    ("video/ogg", "ogg"),
                    ("audio/ogg", "ogg"),
                    ("audio/opus", "opus"),
                    ("audio/x-m4a", "aac"),
                    ("audio/x-m4a", "m4a"),
                    ("audio/m4a", "m4a"),
                    ("audio/x-flac", "flac"),
                    ("audio/flac", "flac"),
                    ("audio/aiff", "aif"),
                    ("audio/x-aiff", "aif"),
                    ("audio/aiff", "aiff"),
                    ("audio/x-aiff", "aiff"),
                ],
                max_length=50,
            ),
        ),
    ]
