# Generated by Django 5.2.11 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


def migrate_artist_fid(apps, schema_editor):
    Artist = apps.get_model("music", "Artist")
    artists = []
    for artist in Artist.objects.filter(
        channel__isnull=False, channel__actor__domain__name=settings.FEDERATION_HOSTNAME
    ):
        artist.fid = artist.channel.actor.fid
        artists.append(artist)
    Artist.objects.bulk_update(artists, ["fid"], batch_size=5000)


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0063_upload_third_party_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("index", models.PositiveIntegerField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["index", "id"],
            },
        ),
        migrations.RunPython(
            migrate_artist_fid, reverse_code=migrations.RunPython.noop
        ),
    ]
