FROM alpine:3.21 AS requirements

RUN set -eux; \
  apk add --no-cache \
  poetry \
  py3-cryptography \
  py3-pip \
  python3

COPY pyproject.toml poetry.lock /
RUN set -eux; \
  poetry export --without-hashes --extras typesense > requirements.txt; \
  poetry export --without-hashes --with dev > dev-requirements.txt;

FROM alpine:3.21 AS builder

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG PIP_NO_CACHE_DIR=1
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

RUN set -eux; \
  apk add --no-cache \
  cargo \
  curl \
  gcc \
  g++ \
  git \
  jpeg-dev \
  libffi-dev \
  libldap \
  libxml2-dev \
  libxslt-dev \
  make \
  musl-dev \
  openldap-dev \
  openssl-dev \
  postgresql-dev \
  zlib-dev \
  py3-cryptography \
  py3-lxml \
  py3-pillow \
  py3-psycopg2 \
  py3-watchfiles \
  python3-dev \
  gfortran \
  libgfortran \
  openblas-dev \
  py3-scipy \
  py3-scikit-learn;

# Create virtual env
RUN python3 -m venv --system-site-packages /venv
ENV PATH="/venv/bin:$PATH"

COPY --from=requirements /requirements.txt /requirements.txt
COPY --from=requirements /dev-requirements.txt /dev-requirements.txt

RUN --mount=type=cache,target=~/.cache/pip; \
  set -eux; \
  pip3 install --upgrade pip;


RUN --mount=type=cache,target=~/.cache/pip; \
  set -eux; \
  pip3 install setuptools wheel;

RUN --mount=type=cache,target=~/.cache/pip; \
  set -eux; \
  # Currently we are unable to relieably build rust-based packages on armv7. This
  # is why we need to use the packages shipped by Alpine Linux.
  # Since poetry does not allow in-place dependency pinning, we need
  # to install the deps using pip.
  grep -Ev 'cryptography|lxml|pillow|psycopg2|watchfiles|scipy|scikit-learn' /requirements.txt \
  | pip3 install -r /dev/stdin \
  cryptography \
  lxml \
  pillow \
  psycopg2 \
  watchfiles \
  scipy \
  scikit-learn;

ARG install_dev_deps=0
RUN --mount=type=cache,target=~/.cache/pip; \
  set -eux; \
  if [ "$install_dev_deps" = "1" ] ; then \
    grep -Ev 'cryptography|lxml|pillow|psycopg2|watchfiles' /dev-requirements.txt \
    | pip3 install -r /dev/stdin \
    cryptography \
    lxml \
    pillow \
    psycopg2 \
    watchfiles; \
  fi

FROM alpine:3.21 AS production

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ARG PIP_NO_CACHE_DIR=1

RUN set -eux; \
  apk add --no-cache \
  bash \
  ffmpeg \
  gettext \
  jpeg-dev \
  libldap \
  libmagic \
  libpq \
  libxml2 \
  libxslt \
  py3-cryptography \
  py3-lxml \
  py3-pillow \
  py3-psycopg2 \
  py3-watchfiles \
  py3-scipy \
  py3-scikit-learn \
  python3 \
  tzdata

COPY --from=builder /venv /venv
ENV PATH="/venv/bin:$PATH"

COPY . /app
WORKDIR /app

RUN apk add --no-cache gfortran
RUN --mount=type=cache,target=~/.cache/pip; \
  set -eux; \
  pip3 install --no-deps --editable .

ENV IS_DOCKER_SETUP=true

CMD ["./docker/server.sh"]
