# Generated by Django 5.1.6 on 2025-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0028_auto_20221027_1141"),
        ("music", "0061_migrate_libraries_to_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="reachable_retries",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
