# Generated by Django 5.1.6 on 2026-01-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0029_domain_reachable_retries"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedActor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emitted_block",
                        to="federation.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_block",
                        to="federation.actor",
                    ),
                ),
            ],
            options={
                "unique_together": {("actor", "target")},
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="blocks",
            field=models.ManyToManyField(
                related_name="blocked_by",
                through="federation.BlockedActor",
                to="federation.actor",
            ),
        ),
    ]
