# Generated by Django 5.2.11 on 2026-02-14 10:39

from django.db import migrations, models


def is_funkwhale_instance(apps, schema_editor):
    Domain = apps.get_model("federation", "Domain")
    domains = []
    for domain in Domain.objects.all():
        if (
            domain.nodeinfo
            and domain.nodeinfo.get("payload", {}).get("software", {}).get("name", None)
            == "Funkwhale"
        ):
            domain.is_funkwhale_instance = True
            domains.append(domain)

    Domain.objects.bulk_update(domains, ["is_funkwhale_instance"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0030_blockedactor_actor_blocked_actors"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_funkwhale_instance",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunPython(
            is_funkwhale_instance, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="actor",
            name="blocks",
            field=models.ManyToManyField(
                related_name="blocked_by",
                through="federation.BlockedActor",
                through_fields=("actor", "target"),
                to="federation.actor",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                through="federation.Follow",
                through_fields=("target", "actor"),
                to="federation.actor",
            ),
        ),
    ]
